#!/usr/bin/env python3
# 机械证据生成：从 regress.mjs 产出的测试 log 提取摘录写入 doc/evidence/，回填 testplan/bugs。
# 证据文件禁止手写；FAIL log 一律拒收（失败走缺陷闭环）。首行 = 可复跑命令。
# 用法（--test 的值必须与产出 log 的那次 make test/e2e TEST=... 完全一致，才能算出同一 log 路径）:
#   python scripts/evidence.py --scen M0-01 --test geo            # 对应 make test TEST=geo
#   python scripts/evidence.py --scen M0-02 --e2e --shot test-results/smoke.png   # 对应 make e2e（无 TEST）
#   python scripts/evidence.py --scen M0-03 --lint                # 对应 make lint
#   python scripts/evidence.py --regress                          # 归档回归总判定
#   python scripts/evidence.py --bug BUG-001 --test xxx           # 复验关单（要求修复commit列已回填）
import argparse
import json
import re
import shutil
import sys
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DOC = ROOT / "doc"
OUT = ROOT / "test-results"
EXCERPT_TAIL = 25

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")


def version():
    return json.loads((ROOT / "version.json").read_text(
        encoding="utf-8"))["version"]


def sanitize(pattern):
    """log 文件名契约：与 scripts/regress.mjs 的 sanitize() 必须逐字符一致。
    显式用 ASCII 字符类——Python 的 \\w 含 CJK 而 JS 的 \\w 不含，直接抄 \\w 会算出不同文件名。"""
    return re.sub(r"[^0-9A-Za-z_.-]", "_", pattern) if pattern else "all"


def verdict_of(text):
    m = re.search(r"^\[regress\] RESULT: (PASS|FAIL)", text, re.M)
    return m.group(1) if m else "NOSUMMARY"


def load_log(path):
    if not path.exists():
        sys.exit("log 不存在（先 make test/e2e/lint）: %s" % path)
    text = path.read_text(encoding="utf-8", errors="replace")
    v = verdict_of(text)
    if v == "NOSUMMARY":
        sys.exit("log 没有机械判定尾行——只有 regress.mjs（make test/e2e/lint）产出的 log 可作证据: %s" % path)
    if v == "FAIL":
        sys.exit("log 判定 FAIL——失败不入证据，先在 doc/bugs.md 登记（来源: %s）" % path)
    return text


def write_record(rid, replay, log_path, spec_ref):
    text = load_log(log_path)
    lines = text.splitlines()
    excerpt = lines[:2] + ["..."] + lines[-EXCERPT_TAIL:] \
        if len(lines) > EXCERPT_TAIL + 3 else lines
    evdir = DOC / "evidence" / ("v" + version())
    evdir.mkdir(parents=True, exist_ok=True)
    rec = evdir / (rid + ".log")
    header = [replay,
              "# Generated by scripts/evidence.py on %s, source log: %s"
              % (date.today().isoformat(), log_path.relative_to(ROOT))]
    if spec_ref:
        header.append("# spec_ref: " + spec_ref)
    rec.write_text("\n".join(header) + "\n\n" + "\n".join(excerpt) + "\n",
                   encoding="utf-8")
    return rec.relative_to(ROOT)


def backfill_table(path, rid, update_cells):
    """按行号定位 `| <rid> |` 行，替换指定列（列号→新值），其余保持原样。
    列号契约与 docs.py 的读取端一致（testplan: 3状态/4证据/5复跑，bugs: 1状态/6复验），改表结构须两侧同步。"""
    lines = path.read_text(encoding="utf-8").splitlines()
    for i, line in enumerate(lines):
        cells = [c.strip() for c in line.strip().strip("|").split("|")]
        if line.strip().startswith("|") and cells and cells[0] == rid:
            if len(cells) <= max(update_cells):
                sys.exit("%s 的 %s 行只有 %d 列，与脚本列号契约不符——先修表结构"
                         % (path.name, rid, len(cells)))
            for col, val in update_cells.items():
                if "|" in val:
                    sys.exit("回填值含 '|' 会破坏表结构: %r" % val)
                cells[col] = val
            lines[i] = "| " + " | ".join(cells) + " |"
            path.write_text("\n".join(lines) + "\n", encoding="utf-8")
            return cells
    return None


def main():
    ap = argparse.ArgumentParser()
    who = ap.add_mutually_exclusive_group(required=True)
    who.add_argument("--scen")
    who.add_argument("--bug")
    who.add_argument("--regress", action="store_true")
    ap.add_argument("--test", default="", help="regress.mjs 的测试模式（决定默认 log 路径）")
    ap.add_argument("--e2e", action="store_true")
    ap.add_argument("--lint", action="store_true")
    ap.add_argument("--log", help="覆盖默认 log 路径")
    ap.add_argument("--spec-ref", default="")
    ap.add_argument("--shot", action="append", default=[],
                    help="随证据归档的截图（可重复）")
    a = ap.parse_args()

    if a.regress:
        src = OUT / "regress_summary.txt"
        load_log(src)
        evdir = DOC / "evidence" / ("v" + version())
        evdir.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(src, evdir / "regress_summary.txt")
        print("[evidence] 回归证据归档: %s" % (evdir / "regress_summary.txt").relative_to(ROOT))
        return

    if a.lint:
        replay, default_log = "make lint", OUT / "lint.log"
    elif a.e2e:
        replay = "make e2e" + (" TEST=%s" % a.test if a.test else "")
        default_log = OUT / ("e2e_%s.log" % sanitize(a.test))
    else:
        replay = "make test" + (" TEST=%s" % a.test if a.test else "")
        default_log = OUT / ("unit_%s.log" % sanitize(a.test))
    log_path = Path(a.log) if a.log else default_log
    if not log_path.is_absolute():
        log_path = ROOT / log_path

    rid = a.scen or a.bug
    rec = write_record(rid, replay, log_path, a.spec_ref)
    for shot in a.shot:
        src = ROOT / shot
        if not src.exists():
            sys.exit("截图不存在: %s" % shot)
        dstp = (ROOT / rec).parent / ("%s-%s" % (rid, src.name))
        shutil.copyfile(src, dstp)
        print("[evidence] 截图归档: %s" % dstp.relative_to(ROOT))

    if a.scen:
        ok = backfill_table(DOC / "testplan.md", rid,
                            {3: "✅", 4: str(rec).replace("\\", "/"),
                             5: "`%s`" % replay})
        if not ok:
            sys.exit("testplan.md 里找不到场景行 %s（先登记后写码）" % rid)
        print("[evidence] %s → ✅  证据: %s" % (rid, rec))
    else:
        # 关单前置条件：修复commit 列（第 5 列）须已回填，否则 CLOSED 行会被 docs-check 拦截
        for line in (DOC / "bugs.md").read_text(encoding="utf-8").splitlines():
            cells = [c.strip() for c in line.strip().strip("|").split("|")]
            if line.strip().startswith("|") and cells and cells[0] == rid:
                if len(cells) > 5 and cells[5] in ("-", ""):
                    sys.exit("%s 的修复commit列未回填——先置 FIX_READY 并填修复 commit，再关单" % rid)
        ok = backfill_table(DOC / "bugs.md", rid,
                            {1: "CLOSED", 6: str(rec).replace("\\", "/")})
        if not ok:
            sys.exit("bugs.md 里找不到 %s" % rid)
        print("[evidence] %s → CLOSED  复验证据: %s" % (rid, rec))


if __name__ == "__main__":
    main()
